# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGraphicsScene

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(594, 443)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 131, 41))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 20, 41, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(169, 20, 271, 41))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(60, 20, 31, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(110, 20, 31, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(160, 20, 31, 16))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(210, 20, 31, 16))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButtons = [self.radioButton, self.radioButton_2, self.radioButton_3, self.radioButton_4, self.radioButton_5, self.radioButton_6, self.radioButton_7]

        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 70, 551, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.groupBox_3)
        self.lcdNumber.setGeometry(QtCore.QRect(220, 10, 101, 21))
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.groupBox_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 40, 531, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 160, 551, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(parent=self.groupBox_4)
        self.lcdNumber_2.setGeometry(QtCore.QRect(220, 10, 101, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(parent=self.groupBox_4)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 40, 531, 31))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 20, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 250, 551, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.scene = QGraphicsScene()
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 320, 551, 71))
        self.graphicsView.setObjectName("graphicsView")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Motor Direction"))
        self.radioButton.setText(_translate("MainWindow", "CW"))
        self.radioButton_2.setText(_translate("MainWindow", "CCW"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Preset Duty Cycle Values"))
        self.radioButton_3.setText(_translate("MainWindow", "0"))
        self.radioButton_4.setText(_translate("MainWindow", "25"))
        self.radioButton_5.setText(_translate("MainWindow", "50"))
        self.radioButton_6.setText(_translate("MainWindow", "75"))
        self.radioButton_7.setText(_translate("MainWindow", "100"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Duty Cycle"))
        self.groupBox_4.setTitle(_translate("MainWindow", "PWM Frequency"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))
