# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGraphicsScene


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 380)
        MainWindow.setFixedSize(725, 380)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.arrayX, self.arrayY, self.arrayXend, self.arrayYend = (20, 10, 401 , 311)
        self.groupBox.setGeometry(QtCore.QRect(self.arrayX, self.arrayY, self.arrayXend, self.arrayYend))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        
        rows, cols = 5, 8
        size, spacing = 45, 2
        first_box_corner = (self.arrayX-10, self.arrayY+20)  
        first_x, first_y = first_box_corner
        box_corners = []
        for row in range(rows):
            for col in range(cols):
                x = first_x + col * (size+spacing)
                y = first_y + row * (size+spacing)
                box_corners.append((x, y))
        self.buttons = {}
        for i in range(len(box_corners)):
            self.buttons[i+1] = QtWidgets.QPushButton(parent=self.groupBox)
            self.buttons[i+1].setGeometry(QtCore.QRect(QtCore.QPoint(box_corners[i][0], box_corners[i][1]), QtCore.QSize(size,size)))
            self.buttons[i+1].setObjectName(f"pushButton_{i+1}")

        self.scene = QGraphicsScene()
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(480, 10, 231, 121))
        self.graphicsView.setObjectName("graphicsView")
        
        
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(480, 140, 231, 81))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 91, 31))
        self.radioButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.radioButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setIconSize(QtCore.QSize(12, 12))
        self.radioButton.setAutoExclusive(True)
        self.radioButton.setObjectName("START")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(160, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("PAUSE")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("RESUME")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(160, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("STOP")
        self.radioButtons = [self.radioButton, self.radioButton_2, self.radioButton_3, self.radioButton_4]
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(60, 0, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.label.raise_()
        self.radioButton.raise_()
        
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(430, 10, 41, 311))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.progressBar = QtWidgets.QProgressBar(parent=self.groupBox_3)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(10, 20, 21, 271))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setAcceptDrops(False)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 29)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(-6, 0, 51, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(0, 290, 41, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_3.raise_()
        self.label_5.raise_()
        self.progressBar.raise_()
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 230, 231, 91))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit = QtWidgets.QTextEdit(parent=self.groupBox_4)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 231, 61))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(0, 70, 231, 17))
        self.pushButton.setObjectName("pushButton")

        self.label_expected_points = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_expected_points.setGeometry(QtCore.QRect(380, 330, 131, 21))
        self.label_expected_points.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_expected_points.setObjectName("label_expected_points")

        self.label_total_points = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_total_points.setGeometry(QtCore.QRect(550, 330, 131, 21))
        self.label_total_points.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_total_points.setObjectName("label_total_points")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.translate = _translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton.setText(_translate("MainWindow", "START"))
        self.radioButton_2.setText(_translate("MainWindow", "PAUSE"))
        self.radioButton_3.setText(_translate("MainWindow", "RESUME"))
        self.radioButton_4.setText(_translate("MainWindow", "STOP"))
        self.label.setText(_translate("MainWindow", "Game Control"))
        self.label_3.setText(_translate("MainWindow", "Target"))
        self.label_5.setText(_translate("MainWindow", "Base"))
        self.pushButton.setText(_translate("MainWindow", "Send"))

        self.label_expected_points.setText(_translate("MainWindow", "Expected Points: 0"))
        self.label_total_points.setText(_translate("MainWindow", "Total Points: 0"))